name: copy_with_gen
description: A generator to make copyWith extension file.
version: 0.1.0
homepage: https://github.com/Caijinglong

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  project: ^0.1.2
  analyzer: ^0.40.6
  dart_style: ^1.3.9
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

executables:
  copy_gen: copy_gen